// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydenmakwfvaozhsegvxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkZW5tYWt3ZnZhb3poc2VndnhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1Njg1MDQsImV4cCI6MjA3MDE0NDUwNH0.pcl4OIzxhfn8aOmaqGcdBobuMLn1zOxiNfrFOt8CxVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});